language: ruby
install:
    - bundle-install --gemfile=./
script:
    - bundle exec rspec
    - bundle exec jekyll doctor
    - bundle exec jekyll build --trace

deploy:
    steps:
        # Push site to AWS S3 bucket
        - s3sync:
            key_id: $AWS_ACCESS_KEY_ID
            key_secret: $AWS_SECRET_ACCESS_KEY
            bucket_url: $AWS_BUCKET_URL
            source_dir: _site/
            opts: |
                --add-header Cache-Control:max-age=60
                --no-preserve
