language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
language: ruby
rvm:
- 2.2.3
before_script:
 - chmod +x ./build_script/cibuild # or do this locally and commit

install:
- bundle install
- npm install cssnano-cli --global
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./build_script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch
  - dev_leanontree_v1_changes_and_fixes
  - dev_leanontree_refactoring

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    skip_cleanup: true
    region: us-west-2
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_DEV
    skip_cleanup: true
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      all_branches: true
